### ISSUE TITLE
PARTICLE_STILT.DAT does not contain any trajectory data

### ISSUE THREAD

**Issue by ankitpatel0698** [uataq/stilt-tutorials#1]
>Used wrfout met data given in https://github.com/uataq/stilt-tutorials/tree/main/03-wrf/wrfout.
>Converted it into .arl format, edited and run r/run_stilt.r.
> But getting the error: myproject/out/by-id/201509060200_-111.847672_40.766189_25/PARTICLE_STILT.DAT does not contain any trajectory data. Check for errors in log.txt
![Screenshot from 2021-02-15 22-49-36](https://user-images.githubusercontent.com/75941016/107976886-47080f00-6fe0-11eb-9eb4-4b25b20fde7d.png)

![Screenshot from 2021-02-15 22-32-42](https://user-images.githubusercontent.com/75941016/107975626-656d0b00-6fde-11eb-8d55-075af8368df0.png)

Help please 
Thanks

**Comment by benfasoli** [comment]
It looks like your STILT install is out of date. Can you try starting a new STILT project for the tutorial to confirm the issue is still happening?

**Comment by ankitpatel0698** [comment]
Dear benfasoli...Yeah it worked thanks. I have following doubts:
1. There's no information about how to use the output of WRF-STILT i.e. What to do after STEP 5 (https://github.com/uataq/stilt-tutorials/tree/main/03-wrf) ? Can you please tell me how i gonna use (plotting) output of wrf-stilt run i.e. footprints inside the directory ./out  for plotting purpose. Will i need to run stilt-tutorials/01-wbb/tutorial.r in case of wrf-stilt run?? 

2. Please enlighten me about **emissions.rds** file (stilt-tutorials/01-wbb/emissions.rds). How to will i create such emission file when i will be using STILT for my experiment?

**Comment by benfasoli** [comment]
The [WBB Tutorial](https://github.com/uataq/stilt-tutorials/tree/main/01-wbb) or [this example](https://gist.github.com/benfasoli/b24caa9aee8c78593dd337412fcdba21) have sample code to visualize the footprint files. The WRF-STILT tutorial just shows how to convert WRF data into a format compatible with STILT (and HYSPLIT >= v5.0.2).

The emissions data typically comes from an emissions inventory but the specifics will depend on your use case, what species you're interested in, and where in the world you are trying to model. The [ODIAC emission data product](https://www.odiac.org/data-product.html) is a global fossil fuel CO2 emissions inventory and would be a good place to start.
