### ISSUE TITLE
difficulty in using <simulation_id>_traj.rds outputs for plotting

### ISSUE THREAD

**Issue by ankitpatel0698** [uataq/stilt-tutorials#3]
As you are familiar; after running the STILT we get two types of output.

1. footprints in .nc (netcdf) format
2. particles tracjectory in .rds format.

From the above outputs I am able to plot footprints using .nc files (e.g. average_footprint.png) but I have no idea how to use .rds outputs.
I am trying to create figures like 'average_contribution.png'. It seems like particle trajectory .rds output are combined with footprints .nc outputs for such figures. I have gone through tutorial.r script which you have used for creating ''average_contribution.html'' but it becomes confusing as that code used "emission.rds" dataset/inventory that is already provided by you in the repository. But here in the output i am getting <simulation_id>_traj.rds files in out/particles folder. 
Can you please help me for creating such plots using <simulation_id>_traj.rds files. Or do you have any code for that?
![average_contribution](https://user-images.githubusercontent.com/75941016/112347826-35a3d800-8ced-11eb-890d-a4c9dbdddc0a.png)
![average_footprint](https://user-images.githubusercontent.com/75941016/112347837-38063200-8ced-11eb-93e1-19a0b40e5a02.png)

**Comment by benfasoli** [comment]
A good place to start would be the example code that demonstrates how to load the `<simulation_id>_traj.rds` files in the [output files documentation](https://uataq.github.io/stilt/#/output-files?id=particle-trajectories).

The trajectories are used internally by STILT to calculate the footprints but shouldn't be needed to reproduce the above figures. You can view the tutorial code [here](https://github.com/uataq/stilt-tutorials/blob/main/01-wbb/tutorial.r) where the above field is generated as the product of the footprint grid and the emission grid.

The footprint grid gives the sensitivity to fluxes originating from each cell. To link observations with gridded emissions, you'll need to download an emission inventory and format it such that the emission matrix dimensions match the footprint matrix dimensions. The specific inventory depends on what species you're interested in and where in the world you are trying to model.

**Comment by ankitpatel0698** [comment]
Thanks again dear benfasoli. 2 more doubts i have
--> numpar (number of particles)  in rstilt.r namelist; depends on what factors. i.e. how should i decide its value 100,200,500,1000 or more?
---> if i want to use tracer concentration (e.g. particle/m3) for a specie, which variable in the rstilt.r is to be edited?
---> where can i find more info and significance about each variables used in rstilt.r namelist?

**Comment by benfasoli** [comment]
You can find documentation for the model configuration parameters on the [STILT website](https://uataq.github.io/stilt/#/configuration) and the [HYSPLIT User's Guide](https://www.arl.noaa.gov/documents/reports/hysplit_user_guide.pdf).

Choosing a higher value for `numpar` will improve simulation accuracy but at the cost of additional computing time (near linear increase in compute duration with increase in ensemble size). Lowering `numpar` will speed up simulations but may result in additional grid noise, especially in the far (>24 hour) field. I'd suggest starting with the default 1,000 particles and modifying if needed depending on your simulation results.

STILT outputs footprints (tracer concentration per unit flux) and not direct tracer concentrations. If you'd like to use the spatial density of the particle ensemble, you can calculate this from the trajectory files. However, directly gridding the spatial density of particles loses out on the benefits of using the footprint calculation algorithm.
